#!/bin/bash
# Place this in $VIRTUALENVWRAPPER_HOOK_DIR, typically ~/.virtualenvs/ directory
# This hook is run after a new virtualenv is activated.

pip install ipdb
pip install ipython
pip install bpython
pip install requests
