#!/bin/bash
# Place this in $VIRTUALENVWRAPPER_HOOK_DIR, typically ~/.virtualenvs/ directory
# This hook is run after a new virtualenv is activated.
pip install --upgrade pip
pip install pdbpp
pip install ipython
pip install bpython
pip install requests
